# Generated by Django 3.1.5 on 2021-04-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Transaction_id',
            new_name='transaction_id',
        ),
    ]
